# Generated by Django 5.0.6 on 2024-08-08 05:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.PositiveIntegerField(choices=[(0, 'Inactive'), (2, 'Active'), (1, 'Migrated'), (3, 'Archived')], default=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('T', 'Text Input'), ('S', 'Select One Choice'), ('MS', 'Multi Choice'), ('R', 'Radiobutton'), ('C', 'Checkbox'), ('D', 'Date'), ('F', 'File')], max_length=2)),
                ('order', models.PositiveIntegerField()),
                ('mandatory', models.BooleanField(default=True)),
                ('validation', models.IntegerField(choices=[(0, 'Digit'), (1, 'Number'), (2, 'Alphabet'), (3, 'Alphanumeric')], max_length=2)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('section_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_name', to='activity.section')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.PositiveIntegerField(choices=[(0, 'Inactive'), (2, 'Active'), (1, 'Migrated'), (3, 'Archived')], default=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField()),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('question_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_name', to='activity.question')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
