# Generated by Django 5.0.6 on 2024-08-08 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_question_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='validation',
            field=models.IntegerField(choices=[(0, 'Digit'), (1, 'Number'), (2, 'Alphabet'), (3, 'Alphanumeric')]),
        ),
    ]
