# Generated by Django 5.0.6 on 2024-08-29 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_alter_question_validation'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='map',
            field=models.BooleanField(default=False),
        ),
    ]
