# Generated by Django 5.0.6 on 2024-08-05 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_menus'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleMainConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Add', models.BooleanField(default=False)),
                ('Edit', models.BooleanField(default=False)),
                ('Delete', models.BooleanField(default=False)),
                ('View', models.BooleanField(default=False)),
                ('Menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_role', to='userprofile.menus')),
                ('Role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_role', to='userprofile.role_type')),
            ],
            options={
                'unique_together': {('Role', 'Menu')},
            },
        ),
    ]
