# Generated by Django 4.2.11 on 2024-07-25 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beneficiaryname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BeneficiaryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beneficiarytype', models.CharField(max_length=100)),
                ('beneficiarycode', models.PositiveIntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(blank=True, choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th'), ('5th', '5th'), ('6th', '6th'), ('7th', '7th'), ('8th', '8th'), ('9th', '9th'), ('10th', '10th'), ('11th', '11th'), ('12th', '12th')], max_length=4, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='profile',
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='gradechoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grdechoice', to='beneficiary.grade'),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Beneficiarytype', to='beneficiary.beneficiarytype'),
        ),
    ]
