# Generated by Django 5.0.6 on 2024-08-21 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiary', '0002_beneficiary_beneficiarytype_grade_delete_profile_and_more'),
        ('demography', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('School_Name', models.CharField(max_length=300)),
                ('School_Code', models.PositiveIntegerField(unique=True)),
                ('School_Locaion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Location', to='demography.location')),
            ],
        ),
    ]
