# Generated by Django 5.0.6 on 2024-08-21 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiary', '0003_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='School', to='beneficiary.school'),
        ),
    ]
